apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: guestbook-ui
  name: guestbook-ui
spec:
  ports:
  - name: "32000"
    port: 32000
    protocol: TCP
    targetPort: 32000
  selector:
    app: guestbook-ui
  type: NodePort
